apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elpai-openschema-prod

resources:
  - ../../base

patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/environment: prod